// src/cities.ts
export const cities = [
  // United States
  'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
  'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose',

  // Europe
  'London', 'Paris', 'Berlin', 'Madrid', 'Rome', 'Vienna', 'Amsterdam',
  'Brussels', 'Zurich', 'Geneva', 'Lisbon', 'Prague', 'Budapest',
  'Warsaw', 'Copenhagen', 'Stockholm', 'Oslo', 'Helsinki', 'Athens',
  'Istanbul', 'Edinburgh', 'Dublin', 'Bratislava', 'Ljubljana',

  // Spain
  'Madrid',
  'Barcelona',
  'Seville',
  'Valencia',
  'Bilbao',
  'Palma de Mallorca',
  'Ibiza',
  'Menorca',
  'Mahón',
  'Sant Antoni de Portmany',
  'San José',
  'Granada',
  'San Sebastián',
  'Zaragoza',
  'Alicante',
  'Oviedo',
  'La Coruña',
  'Salamanca',
  'Badajoz',
  'Almería',
  'Pamplona',
  'Segovia',
  'Toledo',
  'Murcia',
  'Logroño',
  'Jerez de la Frontera',
  'Andratx',

  // Germany
  'Berlin',
  'Munich',
  'Hamburg',
  'Cologne',
  'Frankfurt',
  'Dresden',
  'Stuttgart',
  'Düsseldorf',
  'Leipzig',
  'Nuremberg',
  'Hannover',
  'Bremen',
  'Erfurt',
  'Magdeburg',
  'Kiel',
  'Mainz',
  'Wiesbaden',
  'Potsdam',
  'Karlsruhe',
  'Freiburg',
  'Mannheim',
  'Saarbrücken',
  'Aachen',
  'Cottbus',
  'Rostock',
  'Jena',
  'Tübingen',
  'Bamberg',
  'Würzburg',
  'Kassel',
  'Lübeck',
  'Ulm',
  'Hagen',
  'Heidelberg'
];
